## YAML Template for Taxon API testing
# You'll need to edit this after building...
---
cookieName: taxonApiTest
username: dangunter
password: ""
loginUrl: https://ci.kbase.us/services/authorization/Sessions/Login
taxonUrl: http://euk.kbase.us/taxon
timeout: 1000
objectRef: 993/329/2
