#!/bin/bash
script_dir=$(dirname "$(readlink -f "$0")")

if [ -z $KB_DEPLOYMENT_CONFIG ]
then
    export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
fi

source $script_dir/venv/bin/activate

for api in taxon assembly
do
    echo daemonize -c $script_dir -o $script_dir/$api.stdout -e $script_dir/$api.stderr -a -v $script_dir/venv/bin/python -u $script_dir/venv/bin/data_api_start_service.py --config $KB_DEPLOYMENT_CONFIG --service $api --kbase_url ci
    daemonize -c $script_dir -o $script_dir/$api.stdout -e $script_dir/$api.stderr -a -v $script_dir/venv/bin/python -u $script_dir/venv/bin/data_api_start_service.py --config $KB_DEPLOYMENT_CONFIG --service $api --kbase_url ci
done
