#!/bin/bash
# This script is generally only useful in a KBase deployment environment.

script_dir=$(dirname "$(readlink -f "$0")")

if [ -z $KB_DEPLOYMENT_CONFIG ]
then
    export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
fi

if [ -z $deployenv ]
then

    deployenv=$(grep basename $KB_DEPLOYMENT_CONFIG |cut -f2 -d '=')

    if [ "$deployenv" == 'proda' ]
    then
        deployenv='prod'
    fi
    if [ "$deployenv" == 'prodb' ]
    then
        deployenv='prod'
    fi
fi

source $script_dir/venv/bin/activate

echo starting data_api services in $deployenv environment

for api in taxon assembly genome_annotation
do
    echo daemonize -c $script_dir -o $script_dir/$api.stdout -e $script_dir/$api.stderr -a -v $script_dir/venv/bin/python -u $script_dir/venv/bin/data_api_start_service.py --config $KB_DEPLOYMENT_CONFIG --service $api --kbase_url $deployenv
    daemonize -c $script_dir -o $script_dir/$api.stdout -e $script_dir/$api.stderr -a -v $script_dir/venv/bin/python -u $script_dir/venv/bin/data_api_start_service.py --config $KB_DEPLOYMENT_CONFIG --service $api --kbase_url $deployenv
done
